### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by Pulverizing** [ObliqueNET/Stratos#123]
Hello my name is Pulverizing. I know me attempting to use Discord PMs to buy vouchers is wrong, but about two nights ago someone named AJ something wanted to sell unnamed vouchers, I confronted them that they can't then King_Ibis said it was okay as long as it was unnamed, but if this isn't the case then I promise I will never do it again. Furthermore, my offer for the voucher was either a legendary or a rare HA mon something along that line, that was my intended deal depending if they'd accept it.

**Comment by Pulverizing** [comment]
Hey it's me again, sorry for the rush, but could you guys at least let me know if you guy's are like considering still? I really want to get back on the server and have a great time with my friends and the awesome community. I promise I won't cause anymore trouble.

**Comment by fatyg5** [comment]
This issue with this entire appeal is that your account has already received 5+ warnings/notes from staff about breaking rules. You were also banned for messaging players to use Discord PMs to sell vouchers, which already leads to many questions on why whatever you wanted to do needed to be moved there, and then continued by asking the player in question to do a "secret trade". Due to this, it seems quite obvious that something was trying to be hidden from the staff team, most likely because you knew it was against the rules. Because of this, plus the other instances of breaking rules clearly stated in the /rules of the server, multiple times, you will not be unbanned.

**Comment by Pulverizing** [comment]
As by secret trade, I want to hide from those staff that wanted some of my mons cause I was bothered before that they want the ones I want and it would make them upset I refused their offers for the mon they wanted from me. Please give me one last chance, I promise I will not break anymore rules. If I do then don't ever let me back on
