### ISSUE TITLE
banned bc of alt

### ISSUE THREAD

**Issue by CuteCanary** [ObliqueNET/Stratos#139]
Hi, I was recently IP banned on the server. I'm assuming this is due to me logging on an alt on the server earlier today. I'm sorry about logging the alt on the server. I didn't think it was that big of a deal at the time. I recognize the issue with alt abusing and why it is a rule and I was wrong to think I was an exception with this. I've very much enjoyed playing the server this past week with my friends, and I would love if I had a second chance to do so. I promise I won't log on any alts at all and will continue to follow the 
rest of the rules if given this chance. Thank you for your consideration.

- CuteCanary (the alt was Pebbebengtsson)

**Comment by fatyg5** [comment]
First, I want you to realize /rules exists. If you fail to follow these, you get banned or punished from most servers. One of our biggest rules is exploiting alternate accounts for items, which, you planned to do, as log files show you talking to another player about using the alt for free items by afking overnight. You will be unbanned one day from me closing this ticket, but following this unban, you should read our rules _carefully._

Due to your use of alts, I have limited you to only being able to use one account on the server. Any more will be rejected to log in. If this happens again, you will be permanently banned.
