### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by bagerhoney** [ObliqueNET/Stratos#141]
Hello, 
My ign is bagerhoney and I was banned yesterday for "massive grief." Basically... What happened was that brunobap asked me to make him really high cobble walls around his base for whatever reason, so I did because we are friends, and then he realized he didn't even need them after they were complete (also just to put this out there, the walls were huge because i genned them with water and lava... so he asked for staff to help him take it down). There were no malicious intents and I understand it may have been excessive but I don't believe I should be punished for this because I wasn't griefing him, he asked for it to be done and we are decent friends. I don't feel that the staff member who banned me understood the context surrounding what happened. Thanks for reading and I hope you understand...

**Comment by bagerhoney** [comment]
Id also like to add that I had tried to mine as much as I could before we could get staff involved which shows that I wasnt trying to hurt him :(

**Comment by BootyHadMeLike** [comment]
BruNoBap will tell you that this wasn't an instance of griefing. Both players are friends of mine and this appears to have just been a misunderstanding or a jump to conclusions by staff.

**Comment by fatyg5** [comment]
You bothered staff to clean up an issue that was your own, so of course the staff are going to look into it further. I also have reports from another staff member, who was trying to contain the lava, of bager, himself, "helping" by destroying the blocks the staff member was trying to place to stop the lava from expanding further. 

Whether this was whole incident was intentional or not isn't the issue, the issue is that you asked staff for help and then gave them trouble when they attempted to. Due to this plus your past run-ins with staff members and issues, you won't be unbanned.

**Comment by BootyHadMeLike** [comment]
He was literally trying to stop the lava lol?

**Comment by JustXray** [comment]
I was there when all of this happened. Bager was literally trying to stop the lava from flowing and was unaware staff was trying to use an alternative method until they told everyone to clear out.

**Comment by Forensiic** [comment]
The appeal has been closed. Please don't comment further on it.
