### ISSUE TITLE
Land taken by admin

### ISSUE THREAD

**Issue by NetflixPoptarts** [ObliqueNET/Stratos#159]
Me and my friend while teleporting and looking for a good place for our house found a massive home that was partly destroyed. It was the perfect fit, so my friend and I claimed it and rebuilt some parts of it and built it up. About 3 days later, a staff member deleted Plue’s and my claim as well as our whole town called pods. This land is rightfully ours and these staff members shouldn’t be able to take our land. Thanks for reading.

**Comment by lolanonymous** [comment]
co-ords of where the house?

**Comment by lolanonymous** [comment]
Also the unclaim may have been due to a data issue that unclaimed/deleted some towns, as only admins have permission to delete towns entirely, and we don't do so unless everyone in the town is inactive for 30+ days

**Comment by fatyg5** [comment]
The land was not "taken", our rules state "Do not grief or steal from players, even if it is unclaimed". You found a player's home, that had had it's town deleted from a server issue and claimed over it. I removed your claim because it did not belong to you. That's it. The land is not "rightfully" yours and for that reason, you aren't getting it back.

**Comment by NetflixPoptarts** [comment]
It was partly destroyed and abandoned land that was unclaimed. If it were someone’s land then it would have been in its original form. That’s the reason I say it’s mine. We built up the destruction and it’s very annoying having that be taken away. Also you should not have been able to take away are town because we also had other land either way. This thing is a mess that you really created and I’m not really too happy nor is my friend.

**Comment by NetflixPoptarts** [comment]
Also it’s you taking from us, not the other way around and we are the victims in this situation no matter what.

**Comment by Polylogue** [comment]
Just because someone else also broke the rules and broke blocks in an area that was only unclaimed due to a server error doesn't mean you had a right to the spot. "If it were someone's land it would have been in its original form" is trying to justify not only your evasion of the rules for claiming something you didn't build, but someone else who broke a building that was not theirs to break. 

Imagine if you built something from scratch, something happened while you were away for a weekend, and everything you built and put together was claimed by somebody else. You'd be pissed off.

It was not something you originally built, so it was not yours to claim or rebuild in the first place. This issue is closed, we will not be addressing this further.
