### ISSUE TITLE
Dropping Bug

### ISSUE THREAD

**Issue by YaBoiKirby** [ObliqueNET/Stratos#17]
When dropping items like lets say a full inventory of cobble it only lets you drop half of the stacks. The same goes for the chicken farm, when there are too many chickens they don't lay eggs and don't drop feathers/Chicken. Also when you have the item in your inventory and don't hover over a box in your inventory and click out of your inventory the item will disappear

**Comment by fatyg5** [comment]
Chickens are meant to not drop eggs, feathers, or chicken themselves because mob drops from vanilla mobs are turned off. This was to prohibit players from using hopper farms + chickens to collect drops for sale. 

As for the cobblestone issue, I'd need to see a gif or something to fully test that, as I can't reproduce it.

**Comment by fatyg5** [comment]
After checking with Matt, seems to be able to replicate in the wild only. Very rare occurrence, will look further into it.

**Comment by fatyg5** [comment]
After finally testing this fully, seems to be a limit to how many items you are allowed to drop on the ground before Sponge deletes them. So at the moment, this isn't anything we can fix as it seems intended to reduce ground entity lag.
