### ISSUE TITLE
Banned

### ISSUE THREAD

**Issue by thiagorodriguesnoni** [ObliqueNET/Stratos#191]
Hello oblique!
So I was playing the pixelmon server in oblique and I was in the server stratos and I was walking trying to get pokemons and I got banned from the server and I don't know why and I really like to play pixelmon in the oblique server and I think the server is really good. But after all, can I get unbanned from the server
thankyou
thiagocrod.

**Comment by fatyg5** [comment]
You seriously say you don't know why you got banned? I'm actually shocked. Anyone with a mind to name their town "niggasfc", spam our chat with "Help me" afterwards, so that their town would be shown in chat, and then have the gull to claim they don't know what they did wrong is actually amazing. Since you obviously don't think that doing this was wrong, I don't think that you should be unbanned.
