### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by LanternaLux** [ObliqueNET/Stratos#203]
Minecraft name: LanternaLux
Server banned on: Stratos
Reason for ban, as told by server: Eco breaking?

A while back I decided to take a break from Pixelmon.  So I abandoned my house with all of my chests full of items inside and left.  Someone apparently found my place.  Looted my chests.  Then a mod found out and apparently banned me for "Eco breaking" whatever that is.  I would like to be unbanned as I feel that enough time has passed and after speaking with mods on Terra, I now know that I cannot just give items away and that pokemon have to be traded one for one.  Please unban me.  Thank you.

**Comment by MrBritish8** [comment]
You decided to give away your entire town because you were mad that the server was not spawning legendaries you wanted and the admins had changed the way the legendary bird trio spawned. We do not condone people giving away their entire town, especially when they rage quit from the server. For this, you will not be unbanned
