### ISSUE TITLE
Ban appeal

### ISSUE THREAD

**Issue by CooperEh** [ObliqueNET/Stratos#248]
Hello, good people of Stratos,
IGN: Patrickis
Reason for ban: "Constantly arguing with staff and avoiding mutes"

While playing today a legendary spawned in the end which quickly emerged into a chaos of people trying to capture this elusive Pokemon. Amidst the chaos, different members of staff tried to say something along the lines of "This Hoopa belongs to XXXX" To me (and a few others) a wild pokemon spawn surely would belong to anyone within the vicinity and we couldn't find the specific rule saying that legends are the property of certain people before being captured anywhere in /rules or on the servers discord. So we asked a few questions like: Why isn't this rule written down? What happens if 2 or more people are around a spawn? Do they have to wait for an admins official statement on who it belongs to before attempting a capture? What if a person fails to capture it? Can the rights to a legendary be given from one player to another?

This was a new rule (In the sense that we haven't heard of it before or come across it while reading the rules) so of course, we wanted a clarification of exactly what it meant to prevent confrontations. During these questions, i got muted for 5 minutes for "Arguing with mods" I then hopped on discord to message people privately when I remembered one could use the discord to talk in chat, I double checked both rule sets and found no rule saying that discord isn't to be used while muted in game. Shortly after I was muted for another 10 minutes and then ultimately banned before my mute was up.

http://prntscr.com/nwds8k

http://prntscr.com/nwdscm

I would like to request an unban on the grounds of:
- "Avoiding mute" Isn't specified anywhere as being illegal. You could argue that it's "common sense" but things like "no Xray or hacking" is more common sense, yet written down anyways. This lack of congruence is confusing to players and it seems harsh to ban for without giving due warning.

- In my humble opinion, asking what this unwritten rule entails is not arguing, and I don't see why staff would have a problem clarifying a rule for its players, surely the objective behind a rule is to prevent people from doing said action, but how can people do that when the rule isn't 100% clear.

If you took the time to read what I think are reasonable arguments instead of just thinking "Don't disagree with staff", i thank you for your time.

**Comment by fatyg5** [comment]
I really don't like your attitude regarding this. You tried to avoid a mute, which you yourself claim as common sense, but then say "Why isn't it documented?". The answer: because it's common sense. Some servers for Pixelmon allow some hack mods, so we state the xray and hacking part in our rules. No server gives out a punishment just so you can circumvent it.

Furthermore, this is not unwritten. Our rules clearly state "4. Do not grief or **steal** from others". Just because you chose to not understand the rule does not mean you get some free pass around it. Obviously you read our rules since you knew about xray and hacking. 

Due to this, plus the attitude you had toward our staff, you will not be unbanned.

**Comment by CooperEh** [comment]
"which you yourself claim as common sense" No I didn't, i wrote that some people would argue that and then told you why that arguement doesn't hold up. How can you expect players to live up to a rule if it isn't written?

Also, in my (and others) opinion, the 4th rule "Don't steal" doesn't adequately explain that this applies to any pokemon spawned "on them", especially since players can't check who a pokemon spawned upon. This is why i was asking questions / asking for it to be it's own written rule or atleast clarified so people won't be confused.

I would like for you to elaborate on what you meant by "Attitude toward staff"

**Comment by trezela** [comment]
Maybe the /lg command would help for future instances, that way when a legend spawns ALL people who see it can do /lg and see the exact user it spawned on. I imagine that'd stop some trouble happening in the case of more than one person being in the area? The rule could be that it goes to the /lg name, regardless if how long or not they were there? That or have staff announce who it belongs to immediately, pre-emptively and periodically until it is captured or after a certain timeframe passes [if it becomes clear that that person is afk?] Orrr if y'all want to keep it private due to others ragging on AFKers the staff could message the person it belongs to and if you don't get a private message then you can assume it's not yours, but that'd probably have to be specified in the rules so people would realize to look out for that haha. 

Pardon my nosiness & suggestion/s @_@

**Comment by CenizaRey** [comment]
This issue was closed several hours ago. If you have a suggestion to prevent this instance repeating itself, please take it to #stratos-suggestions on the Discord or make a new thread on the Github.
