### ISSUE TITLE
Banned for reasons unclear

### ISSUE THREAD

**Issue by RedTerra1** [ObliqueNET/Stratos#250]
My in-game name is Axendras
I was banned for the following reasons:

- Arguing with staff
- Being disrespectful towards players
- impersonating staff
The final reason 'impersonating staff' was part of a joke in which the other players of the server joined in and no harm was done so I guess it is understandable but at the time there was no issue.
I would just like some context for the other two reasons I have not been arguing with staff or disrespectful with players to any kind of harsh degree.

-Thanks
Axendras

**Comment by RedTerra1** [comment]
I should also state the ban is only for one-day which is fine, just some clarity regarding the reasons would be nice.

**Comment by Grassip** [comment]
It should be evident that putting in chat "./ban Pokeking_2000 reason:stealing" and then "oops" immediately after in order to portray yourself as someone with the ability to ban would make the player involved uncomfortable and deceive players. Joke or not, you should not have tried to convince people that you were a staff member. 

You have caused trouble multiple times and not been respectful towards staff when told to stop. One instance being earlier today when you said in chat "sup my n-word." You were asked by multiple staff members not to do it again and you responded "its up to the player to decide what it means" and when asked not to talk about it anymore immediately after you pretended not to know what was going on and replied "talking about what?" All of this could have been much easier if you would have simply apologized and dropped the topic, _especially_ considering you were warned not to in the first place.

We have received numerous complaints from a certain player that you were making them uncomfortable and that they were genuinely concerned about being around you and talking to you. You were tempbanned primarily because of that reason. If you feel that you were never making anyone uncomfortable and that it was a misunderstanding you may speak to me privately and we can discuss it further.

**Comment by RedTerra1** [comment]
Honestly, I still fail to identify any of that as 'arguing with staff' no arguments were had and I'm aware of the player of whom you speak, we were having fun with this player yesterday in which there were admins online, had an admin told me to stop then, of course, I would have but it was innocent mindless fun in many people's opinion. Due to the people laughing and the messages I got I was convinced it was easily portrayed as a joke. I apologize for this and can send out an apology to the said player if so desired.

**Comment by Grassip** [comment]
I apologize that you weren't warned when the events were taking place, but the uncomfortable responses of the player should have been a sign that you should have stopped at the time. Remember our first rule: "1. Be respectful to everybody, no matter what." If you are making someone uncomfortable, you are breaking the rules. And yes, I believe you should apologize to the player.
