### ISSUE TITLE
Town Inactivity and Removal

### ISSUE THREAD

**Issue by Manu1218** [ObliqueNET/Stratos#254]
So I've seen several posts about specific towns that need to be deleted, however I was wondering why there hasn't been an implementation of an automatic disbandment of inactive towns. 
I recently faced the situation of finding an inactive town in a terrain that I might've consider for an outpost/town home. But even if I didn't choose that specific region/biome where the inactive town laid, someone else might stumble this region and face the same situation, the inability to build/expand due to an inactive town.
What I want to get to, is that there should be or at least a more efficient way to get inactive towns removed, they really serve no purpose other than occupied chunks. It took more than 3 weeks for staff members to delete a town that had more than +80 days of inactivity...
It is a critic but it wants to serve the purpose of improvement. I see no point on inactive towns. Hope this is read/considered.

**Comment by MrBritish8** [comment]
We do have a system for automatic disbandment of inactive towns, but unfortunately through not fault of our own it is inconsistent with disbanding due to Sponge. So sometimes we need posts like this so we can manually delete the towns. after they are investigated to see if it can help us solve any problems. i understand the issues if you leave the town name i can look into it for you soon when i get on.

**Comment by Manu1218** [comment]
I'll post inactive towns I find, I got no interest in the land they lay on, but might help disband some.

**Comment by Manu1218** [comment]
Lost Seraph is the one town mentioned that's been inactive, i'll close the issue tomorrow by this hour, just in case someone wants to add anything.

**Comment by fatyg5** [comment]
While I appreciate the thought, there is just too many towns to do this for. That's why we do this case-by-case instead. Thank you, though.
