### ISSUE TITLE
I got banend :(

### ISSUE THREAD

**Issue by Squldwerd** [ObliqueNET/Stratos#26]
I am sorry that i was joking a lot around last night. I am sorry for saying to taco that if we called him surface level it would be a insult to the ground floor. I will not do this again and I hope you accept this apology. Have a good rest of your day who ever reads this!

**Comment by fatyg5** [comment]
You were banned for multiple reasons, regarding being rude to staff and ignoring many warnings, not just what you have stated. For that reason, you will not be unbanned.

**Comment by Squldwerd** [comment]
If you wan you can also take away all of my stuff like pokemon to. I just want to play with my friends please.

**Comment by Squldwerd** [comment]
> beaned! jk. We are reviewing server logs, please provide any info related to yours and your friend's ban.

**Comment by ColinSpeight** [comment]
This is megawall, the other person who got banned, I don't think I said much bad, I was bored and wasn't listening to the mod when he told me to stop using caps because I was waiting for a legendary to spawn
I said just because i'm black once or twice which is a true statement and I really don't think I deserve a perm-Ban. Please Help

**Comment by Rasgnarok** [comment]
https://github.com/ObliqueNET/Stratos/issues/31 Just checked that before this. I'll unban you, but know you are on your last warning. None of your alts will be though.
