### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by RedTerra1** [ObliqueNET/Stratos#264]
IGN: Axendras
Banned for 'Continued rudeness to staff'

I do not even know why I've properly been banned this time. The previous ban was understandable from a certain point of view. But all that has happened recently was I was muted for 5 minutes, then when asked why I was then muted for another 30 minutes...any genuine help would be nice
Obviously, it would not happen again if I were to be unbanned as I have a lot of hours on this server but this time it goes pretty damn unwarranted in my opinion.
Thanks.

**Comment by CenizaRey** [comment]
There's a lot to unpack here. I'd like to start with your general attitude towards members of staff during your time on Stratos. So just yesterday, you were running around referring to staff members as "virgins". Which is a little weird, considering we're all playing a game where the target demographic is under 16 years old. So that's one rule broken, the number one rule: "Be respectful to everybody, no matter what."

Okay, part two, your first note comes from an offense you carried out a short while ago where you complained about gym leaders having high IV pokemon. After that was discussed, you continued to bring it up, despite the fact you had been warned by staff several times to drop it. THEN you decided to start encroaching on another player's town, and followed that up by impersonating staff. Whether or not this was a joke is very much your word against ours and this was never a democracy.

Your insults and inappropriate behaviour is what nailed down your coffin, here's a few examples:

"am i gonna get muted again for speaking my mind or we all gonna act like adults?" This was never a democracy, staff can mute you at their discretion if they feel you're being rude or inappropriate, this is in the rules.

"real cringe mate" (in response to a sad face?)

"ever eat ass?" Inappropriate talk, you were warned to change the subject in this case

"i bang my ex" This is again, weirdly inappropriate

"you don't know how long ive wanted to call these losers virgins so much..." This was a private message to who I assume is your friend, Ruben_Fire. You're not stupid. We know you know we can see your ingame PMs. If you were trying to avoid detection by us you would've messaged your friend via another platform. You did this to rock the boat.

But let's review your appeal. Right off the bat you're at a bad start because you haven't owned up to your mistakes. Ban appeals are supposed to be an exhibition of your remorse for breaking the rules. And judging by the fact you said you "have a lot of hours on this server" you should know the rules by now. So you _do_ know why you were banned, you just don't want to admit to your own mistakes despite the fact you have literally nothing to lose.

And finally, "Obviously, it would not happen again" is not an apology. You know you've done wrong, own it, and you might genuinely have a shot at getting unbanned. Until then, Axendras.

**Comment by RedTerra1** [comment]
First of all, good point, I apologise for my behaviour as you're right I have not provided a decent one.
Talking about the high IV pokemon in the gyms was not supposed to come across as an argument or a joke, I was simply suggesting that when a new player first begins on the server they would be attracted to beating the gyms as they will likely play as if it is similar to the original games but with no disclosure that the gym pokemon can be quite powerful with those IVs they can be turned off by that when beaten potentially numerous times. However now I know that the earlier gyms are not as much as an issue as I first thought.

The Pokeking issues were previously discussed and I think mostly an understanding was reached at the time of the joke(in my eyes) there were admins online at the time and not telling me to stop so I was just under the impressions no rules had been broken.

I apologise for the things I said last night, however, I know I saw many people banned last night as people were bantering and having jokes with each other with no intentional harm done.
I do not know Ruben_Fire, but you're right I did message him that because he got the ball rolling with calling them that with the odd talk going on at the time, I have no defence apart for this. The thing is if it's a private message then why does it matter to the other players as it is clearly not directed towards them? I would not actually go about calling them virgins regularly because despite my presented attitude I do not actually want to upset anyone.

I genuinely enjoy playing on the server with you all and I apologise for my actions, you're right I should admit mistake when present. Therefore I apologise.
Thanks.

**Comment by Hiroku** [comment]
One thing that should be aired here is that the server is not the place for edginess or inappropriate language. And I feel it's worth saying, I like an edgy joke, but at the end of the day there are always going to be people on the server that don't see that you're joking, or people who are not joking at all when they say the same shit, or are too young to be getting exposed to inappropriate remarks. That's something a handful of people per week have an issue with, but that's the server you're wanting to be unbanned on so you'll need to face the policy one way or another. It's not a place for the aggression, sexual remarks, or hostility with staff. Make a note of it, since your ban has been reduced to a 2 day tempban, and obviously staff will be unsympathetic if you do more of the same on your return.

Also might be a good idea to think about how to suggest changes without seeming aggressively stubborn lel
