### ISSUE TITLE
Unban request

### ISSUE THREAD

**Issue by MKFusion** [ObliqueNET/Stratos#273]
Can you guys unban me, i did nothing wrong, sharing teams is against the rules doesnt mean that people can copy the same startagie 
if someone spectates a battle at the gyms and make the same exact stategie is he/she going to get banned ?
i mean in my oppinion that was an unfair ban, because i only helped my Town friend who doesnt know as much as I do about pokemon
so if you guys coud Unban me for that i would be appreciated.

**Comment by MKFusion** [comment]
And you guys changed the ban reason 

You guys are so unfair 
a friend of mine was banned 1 time because he used X-Ray he said that he wasnt going to use it again and you guys unban him, days latter you banned them again with no reason what so ever, and he wasnt using X-Ray.

This one of the examples why u guys are so unfair and always do what you want do make you feel better, you dont care about the players you care about yourselfs 

Discusting

**Comment by fatyg5** [comment]
"I want to be unbanned but you guys are horrible"! Great ban appeal, I give it a solid 10/10. You were warned multiple times to not give team-building strategies, team information, or strategies in general to players about exactly how to beat the gyms and you chose not to listen after these multiple warnings. You were then banned for this because of it, made an alternate Discord account after having your original banned, and then wonder why your banned was changed.

I'm sure you can surmise what I'm pointing to in the paragraph above and that is that you will not be unbanned due to your actions, warnings, and the content of this post!

**Comment by MKFusion** [comment]
lissen i gave the strategie 1 TIME, 1 FREAQUING TIME.
They didnt wanr me about the strategie, they warned me about the pokemons to "NOT SWITCH POKEMONS WITH EACH OTHER" and i lissen to that i didnt gave my pokemons again,

it is not my fault to HELP while IN BATTLE to tell the Weknessess of each pokemon and what better attack than others and which pokemons are better than others 

my Friend didnt use THE SAME EXACT POKEMONS WITH EXACT SAME IVS/EVS NATURE, ITEMS as I so I think that doesnt count as a "stratagie"

and yes i created a new discord so i coud have a voice chat with you guys but you prefer to hide and imagine that nothing happened, and I even appeal to Unban me from discord but you prefer not to because like I said You dont care about the players.

And about my firned account You didnt metion it, why??
Because you know its true, because NO ONE IN THAT SERVER USES X-RAY
LeTs BaN aN iNocEnT pLaYer BeCauSe hE iS dOinG NoThiNg AggAinSt ThE RuLes

as I said earlier Discusting
