### ISSUE TITLE
Ban appeal.

### ISSUE THREAD

**Issue by Gomer604** [ObliqueNET/Stratos#276]
Hello,     (2.0)
Today I was wrongly banned by mistake due to a misinterpretation of wording.
I understand it was an accident and they do happen.
No hard feelings, I would like to get back to my legend hunting. :)
I'm sorry you mistaken my phrasing for malicious intent, that was not my plan.
It was just a money maker I didn't want made public.
**_Thanks,
Sincerely,
Forever yours,
Singed,
~Gomer604_**

**Comment by JettisonedGames** [comment]
After thorough deliberation about this ban, it was determined that, while there was some possible miscommunication, you very clearly stated "I'm going to break the economy of this server."  There were discussions on the length of the ban, but, due to the attitude, and you seeming to not think you did anything wrong, the ban will remain.
