### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by TheGameTM** [ObliqueNET/Stratos#280]
Im so sorry for saying racist things. I feel really bad and I understand why i was banned but, I want to be unbanned because i believe people deserve second chances and i will not screw this one up.
IGN: TheGameTM

**Comment by W4nkey** [comment]
Bro don’t give in. They tryna take out right away to say nigger and it’s not okay. #NOBITCHNIGGAS

**Comment by TheGameTM** [comment]
Etika

**Comment by TheGameTM** [comment]
But seriously i really want to get unbanned i was even thinking about buying a rank

**Comment by Grassip** [comment]
Considering you were warned multiple times to stop, you've already had your chances. You were told that saying the n-word was not allowed and then you continued to repeatedly spell the word out in chat. After that you continued making _extremely_ racist jokes. You had plenty of warnings and you knew that what you were doing wasn't allowed. Because of this, you will not be unbanned.

**Comment by TheGameTM** [comment]
Okay i understand but can I get a month ban instead of the Perm ban please its my first time on the server

**Comment by TheGameTM** [comment]
Also, i didnt know pming a friend a racial slur was a bannable offense. Thats why its a "Private Message"

**Comment by W4nkey** [comment]
It’s not these fools just lame I got banned for the same shit while back

**Comment by Rasgnarok** [comment]
Shhhh.
