### ISSUE TITLE
im baned for x ray but i dont x ray

### ISSUE THREAD

**Issue by antoine59970** [ObliqueNET/Stratos#292]
i ave ben baned for x ray whith any explanation and evidence 
![image](https://user-images.githubusercontent.com/52713470/60906915-90c33c00-a278-11e9-8c81-d88a144af979.png)
![image](https://user-images.githubusercontent.com/52713470/60906929-99b40d80-a278-11e9-8747-b61bc0ba7d3f.png)
![image](https://user-images.githubusercontent.com/52713470/60906944-a5073900-a278-11e9-804a-9e982a9f4eb0.png)
my mod texture pack and the resons of ban

**Comment by antoine59970** [comment]
same name in game

**Comment by CenizaRey** [comment]
You were banned due to the fact you were seen teleporting into a cave system and immediately digging into a dungeon that was not visible from where you were. In addition to that, you were also seen trying to open chests in towns you weren’t in. Furthermore, you were also seen bragging that you have “any item”, after finding 3 legendary bells very quickly. Posting screenshots of your mods and resource packs is not evidence you weren’t x-raying, as you can easily remove them from your files.

All the evidence we needed is below. You will not be unbanned.

**Comment by CenizaRey** [comment]
![AF6F5A09-9D79-4C62-AE72-DC4B058DBEF4](https://user-images.githubusercontent.com/42212238/60907766-3de68600-a272-11e9-9466-0b8003b7c894.jpeg)
![431882BE-858E-4127-9241-1291C999E9A4](https://user-images.githubusercontent.com/42212238/60907778-463ec100-a272-11e9-80cc-5c7e62fdcf8f.jpeg)

**Comment by antoine59970** [comment]
i has senn with the lava source
and i lag and find the bell in a unclaim base

**Comment by antoine59970** [comment]
any item is a second message its out of context i ave open a crate an ave loot iv 
i posing a question at this moment

**Comment by antoine59970** [comment]
I saw the lava flow and the massy stone
