### ISSUE TITLE
Ban appeal Madnessrider

### ISSUE THREAD

**Issue by Madnessrider** [ObliqueNET/Stratos#298]
Hey me again, sorry for interrupting you again, but I understand I was stupid and should have never download xray. But I'm not seeing a 3 day ban for saying lazy bastards as a real harsh offense. I really enjoyed my time on the server, so could I have an unban please, I've been punished for a few days now, let me show you, I can do it right too.

**Comment by Grassip** [comment]
A 3 day ban is considered an offense. You broke the rules, you had to pay for it, thus you no longer have a good history. Also, you didn't _just say lazy bastards._ You called one of our admins a lazy bastard along with another player. That's considered disrespecting staff and being disrespectful towards another player, both rules that you have broken due to that. 

As for your ban, once again you had x-ray, which, after playing on the server for a decent amount of time time, you knew was against the rules but chose to attempt to use it anyway. Due to that fact you will not be unbanned.
