### ISSUE TITLE
banned

### ISSUE THREAD

**Issue by MrBlueWolf** [ObliqueNET/Stratos#303]
i dont know why ive got banned the only thing i told him he can win starter pokemons and the prizes even was on the signs i told to dovah to tpa to me to show him the proof but he just banned pls watch this and thanks for your time.

**Comment by Grassip** [comment]
You were banned because you were misleading players and scamming them into spending money. You lied about having an HA staryu as a prize in the casino, and you were deceiving players and using rigged games to swindle money from players. Due to this, you are going to wait the full two days to be unbanned. Also, we have spoken to KFC, he has agreed to shut down the casino. Don't try and rig games like that again, or it will be a perm ban.
