### ISSUE TITLE
Jkaem Ban Appeal

### ISSUE THREAD

**Issue by JkaemtheGOAT** [ObliqueNET/Stratos#313]
Hi, I got banned for knowing sahv was a guy and for posting a clown picture in general chat as a meme. My ban reason says that I have been warned multiple times for disrespecting staff which is not true.

**Comment by Grassip** [comment]
Hahahahahh. No.

You have been the cause of trouble and hate for months. Not only on the server but also on Discord. I don't think I even need to explain this any further. I know for a fact you were warned plenty of times, and that your ban was because you had been arguing and disrespecting our staff members on discord. Don't appeal to me again.
