### ISSUE TITLE
banned need to know the reason and if i can be unbanned 

### ISSUE THREAD

**Issue by MrBlueWolf** [ObliqueNET/Stratos#321]
hello today i got banned  i saw the reason for makes jokes after told but i dont know what joke i typed all i know that my screen turned black and i fixed it i saw that ive got banned and wanted to know if we can talk about this and if in any help i can get unbanned thank you for your time.

**Comment by Grassip** [comment]
Hi Blue,

You were banned because of your comments on school shootings.
As seen here, you spoke about them and then continued to talk about shootings after Dough asked you to drop the subject:
![image](https://user-images.githubusercontent.com/47408346/66665980-a6505500-ec1d-11e9-903d-de7d20a657f6.png)
Next time a staff member asks you to drop a subject, please do so otherwise it will result in a ban, as it has here. 
I know you are not from the US, and therefore may not completely understand how sensitive a subject school shootings are to the kids that live here. It may be fun to joke about with people you know, but joking about them/talking about them publicly where people who may be uncomfortable hearing about it is not okay. You never know when you could be talking about something that somebody else has experienced themselves, so it's always best to think about what you say before you say it. 

If you ever have any questions about topics that you wish to talk about, but think might be inappropriate for a public setting, you can always message me or the other leads for clarification.

That being said, because I understand that you may not have completely understood the intensity of the situation, I am going to shorten your ban to a 3-day temp ban.
