### ISSUE TITLE
Ban Appeal for Its_Akashii 

### ISSUE THREAD

**Issue by Itz-Akashii** [ObliqueNET/Stratos#334]
What I did was wrong and i went a against server rule (TBH i just barely read them) So i am in the wrong but I'm willing to take this actions that we're put upon me. I'd like to join back on the server cause it was really fun. If not I understand my actions were wrong and I'll leave. P.S. this is the only game i can play with my friends. Disregard this last comment.

**Comment by Grassip** [comment]
Due to you attempting to bypass the mod team's socialspy by using discord *after being warned that what you were doing was wrong*, I'm not going to allow you back onto the server. The fact that you immediately went to discord after being warned by a staff member shows me that you have no respect for the server's rules whether or not you know them.
