### ISSUE TITLE
Nevma banned

### ISSUE THREAD

**Issue by Nevma1** [ObliqueNET/Stratos#336]
I was banned for scamming? i traded a event weezing for a expall i asked him if he could trade it to me on a Poke so i wouldnt get scammed. He sent me an Eevee with no item and then dropped me the exp all. never did i see him ask for the eevee back. then i got frozen at the battle frontier cause apparently he thought i scammed him? i sent him the Eevee back and told the admin to tell the kid to be more fucking specific because i didn't think i should have anymore contact with him. I don't think this denotes a ban.

**Comment by JettisonedGames** [comment]
After thorough discussion with our moderation team, your ban will remain until the 1 day has expired.  It is strictly against our rules to go after other players in this manner, and it should have been understood that the Eevee was not part of the deal and should have been returned before a staff member had to step in.  You also were frozen due to being unresponsive multiple times when a staff member stepped in.  For this, your ban will remain until its expiration, at which time you will be welcomed back to Oblique Stratos.
