### ISSUE TITLE
Ban appel

### ISSUE THREAD

**Issue by Dark21424** [ObliqueNET/Stratos#339]
ok i got banned for stealing stuff and begged the staff for mercy couse i did something  really bad and i didnt read the rules couse it was my 2 day playing the server .

<3 Dark21424 also know as Luficer aka the devil

**Comment by Grassip** [comment]
Hi, not only did you obviously know that what you were doing was wrong, you also decided to harass my staff member and in appropriately pester him to the point that he had to ignore you. 

You will not be unbanned due to your lack of maturity towards our staff members along with the damage you did while destroying the items you took.

![unknown-12](https://user-images.githubusercontent.com/47408346/70407733-718d2e00-1a13-11ea-8c6b-dafb5fb8aca3.png)
![unknown-20](https://user-images.githubusercontent.com/47408346/70407734-718d2e00-1a13-11ea-81dc-a0c45607e827.png)

**Comment by Dark21424** [comment]
Hahaha haha aha
 
ill enjoy my self with u When ur time is over

**Comment by Grassip** [comment]
Sounds great see you then

**Comment by Rasgnarok** [comment]
@Dark21424 Aren't you a gross little kid. Consider your ban extended to wherever I find you :)
