### ISSUE TITLE
Unban Request

### ISSUE THREAD

**Issue by MKFusionn** [ObliqueNET/Stratos#344]
So its been a year since i got banned, and my friends have been playing a lot recently on your server,  I was wondering, its been so long and I realy did put efford on your server i realy was... I dont quite remember all the things that i said before but i promiss that i will never do it again, if you could appreciate my request it will mean a lot to me.

Kindly waiting for your feedback

**Comment by Rasgnarok** [comment]
What is your username in game?

**Comment by MKFusionn** [comment]
MK_Fusion

**Comment by Grassip** [comment]
Hi MK! 

I have decided that we will give you a second chance. If you recall, one of the reasons you were banned was simply due to respect towards other players and staff. Please remember to be respectful to everyone, to be respectful of the rules in both the minecraft server and the discord server, and to refrain from starting any arguments, and we won't have any problems. You will now be unbanned, so enjoy your time back on Stratos \o/
