### ISSUE TITLE
Ban appeal. 

### ISSUE THREAD

**Issue by Leonidas9798** [ObliqueNET/Stratos#347]
Some while ago i was banned, Mattblower was the one who told lies about the situation and at the time i was not believed because he was staff and held in higher regard, but more recently he was found to be an untrustworthy person and banned for it, it does not seem right that by a liars statement i should remain banned that would be very sanctimonious and hold his values above my own and morally degrade standards. 
![Screenshot (425)](https://user-images.githubusercontent.com/57264944/73754777-ed190c00-4732-11ea-8785-3e09730014c9.png)

**Comment by Grassip** [comment]
Hi there!

Considering Mattblower wasn't involved in our decision to ban you, I think it's safe to say that you weren't banned by a "liars statement." You chose to try and make it seem as though it was one of our staff's fault for your rulebreaking, and chose to blame him rather than apologize for the things that initially got you banned in the first place. I don't know what you thought blaming Matt for this would accomplish considering I'm almost positive that at the time of your ban Matt wasn't even on my moderation team, so I'm going to keep you banned due to the fact that you chose to blame others instead of apologizing.
