### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by BlueEarl** [ObliqueNET/Stratos#355]
I got my account banned on this because my brother was on my account and he said a bad word and he built a bad object. I just wanna play pokemon can i please be unbanned.

**Comment by fatyg5** [comment]
I find it hard to believe that your brother just so happened to break the rules not once, not twice, but three times without you knowing. Due to this, and the fact that we can not guarantee that someone won't use your account to break our rules again, you will not be unbanned.

My word of advice for you in the future is to not let other people onto your account.
