### ISSUE TITLE
BAN APPEAL 2

### ISSUE THREAD

**Issue by commanderhappy101** [ObliqueNET/Stratos#357]
I Am Sorry For What I did I wont Say the nword again But in my defense there was more than one person doing it SO I TOOK THE BLAME FOR ANOTHER PERSON as well  And In MY offense There is a command /mute Just saying That Would Be more approite But iam just a dumb player what do I know  
But Yes I am Trueley sorry Also This Was On Stratos
Commander_happy

**Comment by Grassip** [comment]
Hi there,

You say you are taking the blame for others, yet you and you only are responsible for your own actions. We take racism on this server very seriously, and you do not seem to genuinely understand your wrongdoings considering you blamed other people for your choice of actions. We thank you for apologizing, but you have tried to make excuses for your actions as well to attempt to make it seem as though you did nothing wrong. Because of that, and the fact that in your last appeal you did not seem like you would genuinely do your best not to break the rules again,  you will not be unbanned.

Have a good day!

Grassi

**Comment by commanderhappy101** [comment]
I took the blame for my self and another person
