### ISSUE TITLE
Ban Appeal 2020

### ISSUE THREAD

**Issue by simonomalm** [ObliqueNET/Stratos#359]
Account: smalm77

I believe I was banned on the 15th or 16th of April last year for racism, spam and disrespect towards staff members which I'm at this time not gonna deny. At the time of it happening I thought it was wrong to ban me, but that's just because I was in a bit different and less mature headspace. I sent a photoshopped picture of a chef with a swastika in the back to an admin on Discord, I spammed the Discord server with a picture of McJuggerNuggets and now that I think back on it I was disrespectful from time to time. Actually I didn't mean to send the racist photo, but I still did it. I regretted everything I did big time after a couple of weeks and I've realized long ago that I was in the wrong. Oblique is BY FAR the best Pixelmon server both me and all my friends have ever played and that's no cap. If you believe me when I say I have changed then please unban me. I would never behave like that again.

**Comment by Grassip** [comment]
Hi there!

I remember what happened, but since it was so long ago and your appeal is genuine I will allow you to come back. Be aware that if the behavior you exhibited to me last year occurs again, you will not be given another chance. We take racism very seriously on Oblique. 

Also, since you are coming back, I do recommend that you fill yourself in on the latest news channels on the Stratos and Oblique discord announcements, because a lot of changes are going to be made within the next few weeks! 

Have a good rest of your day!

Grassi
