### ISSUE TITLE
Block Radius Updates

### ISSUE THREAD

**Issue by Vohras2** [ObliqueNET/Stratos#41]
Currently, beacons and furnaces stop working when you are but a few blocks away from them.

**Comment by fatyg5** [comment]
Currently this is like this because of our sponge configs, I would assume. I'm not sure the actual server lag that can be caused by beacons, as I don't really know how they work, but if I assume that it must constantly check the radius around it for players, seems like it may cause significant issues. Either way, needs testing or confirmation that it won't cause issues before upping the range again.

**Comment by MattBlower** [comment]
Not sure on this one as we have a beacon in our town with no issues having been reported to me

**Comment by Vohras2** [comment]
Sorry Faty, this was meant for Terra.

**Comment by fatyg5** [comment]
Ah, okay!
