### ISSUE TITLE
Ban Appeal (Tjrhino)

### ISSUE THREAD

**Issue by Tjrhino** [ObliqueNET/Stratos#45]
The alleged crime i am being punished for was Duping IV Vouchers. I got some Anecdotal evidence which is garbage. Then i have my word of mouth evidence to prove where i gotten them from. There's no way for me to show you a screenshot of every one I've gotten when but I've been on a hard grind for 2 weeks with running through this game. I've been selling random mons i find and in mesa i got lairons bagons and beldums I've sold for some easy ish cash. everyday i fish up and sell enchantment books for quick flips to afford my gambling addiction in diamond chests. I'm on for about 12-14 hours at a crack investing a lot of time into this. I opened about 10-12 crates a day. saving anything poke item i have figuring id use them but most people sell their mons pretty cheap for 5-6iv so i kept till needed. i bought a couple from people for like 6-7k when they've opened then matt said he'd pay 20k for em i got rid of em. I love the server and im freaking out that i cant be playing rn.

**Comment by Fuklz** [comment]
I certainly did not dislike you as a player, and I myself was not even suspicious when you offered me those 10iv vouchers for money and breeds, as I've never gotten one myself. But getting some knowledge on how rare they are and how much money would have to be dropped to be even statistically likely to get at least 10 of them, I can't help but admit that you were doing some sort of duping. I don't agree with fully banning you but I do think you deserve to lose most of your money and items and be banned from ever redeeming a voucher, at the very least.

**Comment by Tjrhino** [comment]
ive never even redeemed a voucher

**Comment by Fuklz** [comment]
> ive never even redeemed a voucher

That has nothing to do with what I said, mistreating vouchers in general means you deserve to not be able to use them.

**Comment by fatyg5** [comment]
I'm trying to fathom how it's possible for a player, you, who joined on January 5th of this year, managed to get more IV vouchers in 2 weeks than anyone has ever gotten in the history of the server.

The obvious evidence is in the safetrade logs, which clearly shows you selling IV vouchers before the plugin was fixed, to players such as Matt and Fuklz, and then them giving you cash for them. Since the plugin was broken, this means that the plugin was also giving you the items you traded them back, so basically you were trading them, taking their money, and losing nothing. 

This is also supported by chest logs too, showing you removing items, then later placing them (and more than originally had) back into the chest. 

For this reason, you will not be unbanned, sorry.

**Comment by Tjrhino** [comment]
I figured that's how'd it go. well since im nt getting unbanned might as well tell the truth. At one point when i had 2 vouchers i sold them and system gave me 1. thats the furthest ive done duping. i sold all the 10 i had. 4 i bought. 6 i opened, and over 900k for them. i was just here for the people and the crates. Its been a good run.

**Comment by Tjrhino** [comment]
later fam
