### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by AustinNTK** [ObliqueNET/Stratos#5]
I was banned by the server owner for "arguing intentionally with staff" which I wasn't, it started as me trying to find out more about the legendary changes. She must have taken it as arguing but, I was only trying to find out about more about the changes. We talked about a couple things, I threw out some opinions about some legendaries and she then proceeded to tell I was bad at the game. I told her it was childish to do such a thing in a place where she was supposed to be somewhat professional. She then wished to argue about luck, statistics, and how a pokemon was better than the rest because of some "meta" I tried to explain to her that meta can be broken throughout multiple things and how Rayquaza couldn't be the best. She was starting to get sarcastic and saying why its "so simple" for someone to understand. I sarcastically said, " No I just argue with you for fun, you didn't know that?" and she took it offensively, said she now no longer had to "waste her time" with me which is something I think no Owner should say to a player on their server. I was then banned from the discord, blocked on pms, banned from the server I played on daily and had no issues with, and called names from the owner of it in the end. Whether or not she stays as an owner I don't care for but, I don't believe should be banned for giving my opinion nor trying to state my claim

**Comment by AustinNTK** [comment]
While also on the topic of "wasting her time". She could've left at any time and not have kept going on with me and ended it there

**Comment by Rasgnarok** [comment]
You argued about many, many unfounded things. When explained why exactly you were not exact about your claims (such as the legend spawning mechanism, or yes, the usability of Pokemon), you continued to argue and ultimately stated that you just argue to argue. Causing issues within the network just because you can means I have to remind you the last time you were banned - specifically for using racist language and maintaining that defense despite being explained _why_ it is offensive.

Regardless, I see here you have issues a refund based on "authorized activity", which I will go forward and dispute considering **you** made the purchase. It isn't a false purchase (since you truly did purchase something, and consumed said purchase), and should you bring false claims to the network, I will make sure you are justly answered.

Your appeal is denied. Have a good day.

**Comment by AustinNTK** [comment]
cunt

**Comment by AustinNTK** [comment]
Again learn some culture and since no racism was said in this event nor the first one this just proves the amount of bullshit you produce if you wanna be a snowflake go ahead but don't bring it on to other people

**Comment by AustinNTK** [comment]
It is pretty funny though even after other people explain it to you. You still don't understand and are too stupid to understand it. The culture around you is changing get used to it you old fucking foagie

**Comment by Rasgnarok** [comment]
Leave.

**Comment by AustinNTK** [comment]
Fuck off. And grow up
